# Generated by Django 5.0.7 on 2024-07-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
